import apple from "../image/apple.png"
import play from "../image/play.png"
import humo from "../image/humo.png"
import mir from "../image/mir.png"
import paypal from "../image/pay pal.png"
import kivi from "../image/qivi.png"
import pay from "../image/pay.png"
import sber from "../image/sber.png"
import visa from "../image/visa.png"
import veb from "../image/veb.png"
import youtube from "../image/youtube.png"
import whatsapp from "../image/whatsapp.png"
import telegram from "../image/telegram.png"
import instagram from "../image/instagram.png"
import tik from "../image/tik-tok.png"
